openapi: 3.0.3
info:
  contact:
    email: support@run.ai
    name: Run.AI
    url: https://www.run.ai/
  description: An API for creating trials.
  title: Trials
  version: "1.0"
servers:
- url: https://app.run.ai
- url: https://staging.run.ai
- url: https://test.run.ai
- url: http://localhost:8080
paths:
  /:
    get:
      operationId: health
      responses:
        "200":
          description: Executed successfully.
      summary: health check
      tags:
      - health
      x-runai-team: Sphinx
      x-no-authorization: true
    x-internal: true
  /api/v1/trials:
    post:
      operationId: create_trial
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TrialCreationRequest'
        description: The trial to create.
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrialCreationResponse'
          description: Trial Created
        "400":
          content:
            application/json:
              example:
                code: 400
                message: Required parameter is missing
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad request.
        "409":
          content:
            application/json:
              example:
                code: 409
                message: Resource with this name already exists
              schema:
                $ref: '#/components/schemas/Error'
          description: The specified resource already exists
        "500":
          content:
            application/json:
              example:
                code: 500
                message: Something went wrong.
              schema:
                $ref: '#/components/schemas/Error'
          description: unexpected error
        "503":
          content:
            application/json:
              example:
                code: 503
                message: Please try again in few minutes.
              schema:
                $ref: '#/components/schemas/Error'
          description: unexpected error
      summary: Create new trial
      tags:
      - trials
      x-runai-team: Sphinx
      x-test-coverage: not-applicable
      x-no-authorization: true
    x-internal: true
  /api/v1/trials/state:
    get:
      operationId: get_trial_state
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrialsStateResponse'
          description: trials state data
        "400":
          content:
            application/json:
              example:
                code: 400
                message: Required parameter is missing
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad request.
        "500":
          content:
            application/json:
              example:
                code: 500
                message: Something went wrong.
              schema:
                $ref: '#/components/schemas/Error'
          description: unexpected error
        "503":
          content:
            application/json:
              example:
                code: 503
                message: Please try again in few minutes.
              schema:
                $ref: '#/components/schemas/Error'
          description: unexpected error
      summary: get trials state
      tags:
      - trials
      x-runai-team: Sphinx
      x-test-coverage: not-applicable
      x-no-authorization: true
    x-internal: true
  /api/v1/trials/{trialId}:
    get:
      operationId: get_trial
      parameters:
      - description: The id of the trial
        explode: false
        in: path
        name: trialId
        required: true
        schema:
          example: 123e4567-e89b-12d3-a456-426614174000
          format: uuid
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Trial'
          description: trial data
        "400":
          content:
            application/json:
              example:
                code: 400
                message: Required parameter is missing
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad request.
        "401":
          content:
            application/json:
              example:
                code: 401
                message: Issuer is not familiar.
              schema:
                $ref: '#/components/schemas/Error'
          description: Unauthorized
        "403":
          content:
            application/json:
              example:
                code: 403
                message: You do not have sufficient permissions.
              schema:
                $ref: '#/components/schemas/Error'
          description: Forbidden
        "404":
          content:
            application/json:
              example:
                code: 404
                message: Resource id not found.
              schema:
                $ref: '#/components/schemas/Error'
          description: The specified resource was not found
        "500":
          content:
            application/json:
              example:
                code: 500
                message: Something went wrong.
              schema:
                $ref: '#/components/schemas/Error'
          description: unexpected error
        "503":
          content:
            application/json:
              example:
                code: 503
                message: Please try again in few minutes.
              schema:
                $ref: '#/components/schemas/Error'
          description: unexpected error
      summary: Get trial by id
      tags:
      - validated_trials
      x-runai-team: Sphinx
      x-test-coverage: not-applicable
      x-no-authorization: true
    x-internal: true
  /api/v1/trials/{trialId}/verify:
    post:
      operationId: verify_trial
      parameters:
      - description: The id of the trial
        explode: false
        in: path
        name: trialId
        required: true
        schema:
          example: 123e4567-e89b-12d3-a456-426614174000
          format: uuid
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VerifyTrialRequest'
        description: Tenant data
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/verify_trial_200_response'
          description: trial verification tenant created
        "400":
          content:
            application/json:
              example:
                code: 400
                message: Required parameter is missing
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad request.
        "401":
          content:
            application/json:
              example:
                code: 401
                message: Issuer is not familiar.
              schema:
                $ref: '#/components/schemas/Error'
          description: Unauthorized
        "403":
          content:
            application/json:
              example:
                code: 403
                message: You do not have sufficient permissions.
              schema:
                $ref: '#/components/schemas/Error'
          description: Forbidden
        "404":
          content:
            application/json:
              example:
                code: 404
                message: Resource id not found.
              schema:
                $ref: '#/components/schemas/Error'
          description: The specified resource was not found
        "409":
          content:
            application/json:
              example:
                code: 409
                message: Resource with this name already exists
              schema:
                $ref: '#/components/schemas/Error'
          description: The specified resource already exists
        "500":
          content:
            application/json:
              example:
                code: 500
                message: Something went wrong.
              schema:
                $ref: '#/components/schemas/Error'
          description: unexpected error
        "503":
          content:
            application/json:
              example:
                code: 503
                message: Please try again in few minutes.
              schema:
                $ref: '#/components/schemas/Error'
          description: unexpected error
      summary: Verify trial
      tags:
      - validated_trials
      x-runai-team: Sphinx
      x-test-coverage: not-applicable
      x-no-authorization: true
    x-internal: true
  /api/v1/trials/{trialId}/resend:
    post:
      operationId: resend_email
      parameters:
      - description: The id of the trial
        explode: false
        in: path
        name: trialId
        required: true
        schema:
          example: 123e4567-e89b-12d3-a456-426614174000
          format: uuid
          type: string
        style: simple
      responses:
        "200":
          description: Trial email resent successfully.
        "400":
          content:
            application/json:
              example:
                code: 400
                message: Required parameter is missing
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad request.
        "500":
          content:
            application/json:
              example:
                code: 500
                message: Something went wrong.
              schema:
                $ref: '#/components/schemas/Error'
          description: unexpected error
        "503":
          content:
            application/json:
              example:
                code: 503
                message: Please try again in few minutes.
              schema:
                $ref: '#/components/schemas/Error'
          description: unexpected error
      summary: Resend a trial email
      tags:
      - trials
      x-runai-team: Sphinx
      x-test-coverage: not-applicable
      x-no-authorization: true
    x-internal: true
components:
  parameters:
    trialId:
      description: The id of the trial
      explode: false
      in: path
      name: trialId
      required: true
      schema:
        example: 123e4567-e89b-12d3-a456-426614174000
        format: uuid
        type: string
      style: simple
    validation:
      description: A validation code
      explode: true
      in: query
      name: validation
      required: true
      schema:
        type: string
      style: form
  responses:
    "400BadRequest":
      content:
        application/json:
          example:
            code: 400
            message: Required parameter is missing
          schema:
            $ref: '#/components/schemas/Error'
      description: Bad request.
    "409Conflict":
      content:
        application/json:
          example:
            code: 409
            message: Resource with this name already exists
          schema:
            $ref: '#/components/schemas/Error'
      description: The specified resource already exists
    "500InternalServerError":
      content:
        application/json:
          example:
            code: 500
            message: Something went wrong.
          schema:
            $ref: '#/components/schemas/Error'
      description: unexpected error
    "503ServiceUnavailable":
      content:
        application/json:
          example:
            code: 503
            message: Please try again in few minutes.
          schema:
            $ref: '#/components/schemas/Error'
      description: unexpected error
    "401Unauthorized":
      content:
        application/json:
          example:
            code: 401
            message: Issuer is not familiar.
          schema:
            $ref: '#/components/schemas/Error'
      description: Unauthorized
    "403Forbidden":
      content:
        application/json:
          example:
            code: 403
            message: You do not have sufficient permissions.
          schema:
            $ref: '#/components/schemas/Error'
      description: Forbidden
    "404NotFound":
      content:
        application/json:
          example:
            code: 404
            message: Resource id not found.
          schema:
            $ref: '#/components/schemas/Error'
      description: The specified resource was not found
    "204NoContent":
      description: No Content.
    "400BadSubmissionRequest":
      content:
        application/json:
          example:
            code: 400
            message: The workload request does not comply with the policy set by the
              administrator
          schema:
            $ref: '#/components/schemas/SubmissionError'
      description: Bad submission request.
    "406NotAcceptable":
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      description: Not acceptable request
    "412PreconditionFailed":
      content:
        application/json:
          example:
            code: 412
            message: Precondition failed
          schema:
            $ref: '#/components/schemas/Error'
      description: The specified resource was not found.
    "413RequestEntityTooLarge":
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      description: Request entity too large
    "415UnsupportedMediaType":
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      description: Unsupported media type
    "501NotImplemented":
      content:
        application/json:
          example:
            code: 501
            message: Not implemented
          schema:
            $ref: '#/components/schemas/Error'
      description: unexpected error
  schemas:
    TrialCreationRequest:
      example:
        firstName: name
        lastName: lastName
        company: runai
        email: first@run.ai
        isSignedEula: true
      properties:
        firstName:
          minLength: 1
          pattern: "^[a-zA-Z0-9 ]+$"
          type: string
        lastName:
          minLength: 1
          pattern: "^[a-zA-Z0-9 ]+$"
          type: string
        company:
          minLength: 1
          pattern: "^[a-zA-Z0-9 ]+$"
          type: string
        email:
          format: email
          minLength: 3
          pattern: "^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$"
          type: string
        isSignedEula:
          type: boolean
      required:
      - company
      - email
      - firstName
      - isSignedEula
      - lastName
      type: object
    TrialCreationResponse:
      example:
        trialId: 123e4567-e89b-12d3-a456-426614174000
      properties:
        trialId:
          format: uuid
          type: string
      required:
      - trialId
      type: object
    Error:
      example:
        code: 400
        message: Bad request - Resource should have a name
      properties:
        code:
          maximum: 599
          minimum: 100
          type: integer
        message:
          type: string
        details:
          type: string
      required:
      - code
      - message
    ClusterIdOptional:
      description: The id of the cluster.
      example: 71f69d83-ba66-4822-adf5-55ce55efd210
      format: uuid
      minLength: 1
      nullable: true
      type: string
    TrialState:
      example:
        trialId: 123e4567-e89b-12d3-a456-426614174000
        tenantName: runai
        tenantDomain: runai.run.ai
        email: test@run.ai
        company: runai
        tenantId: 123e4567-e89b-12d3-a456-426614174000
        clusterId: 123e4567-e89b-12d3-a456-426614174000
        clusterStatus: connected
        firstLogin: 2020-01-01T00:00:00Z
      properties:
        trialId:
          nullable: true
          type: string
        tenantName:
          nullable: true
          type: string
        tenantDomain:
          nullable: true
          type: string
        email:
          nullable: true
          type: string
        company:
          nullable: true
          type: string
        tenantId:
          nullable: true
          type: string
        clusterId:
          description: The id of the cluster.
          example: 71f69d83-ba66-4822-adf5-55ce55efd210
          format: uuid
          minLength: 1
          nullable: true
          type: string
        clusterStatus:
          nullable: true
          type: string
        firstLogin:
          format: date-time
          nullable: true
          type: string
      required:
      - clusterId
      - clusterStatus
      - company
      - email
      - firstLogin
      - tenantDomain
      - tenantId
      - tenantName
      - trialId
      type: object
    TrialsStateResponse:
      items:
        $ref: '#/components/schemas/TrialState'
      type: array
    Trial:
      example:
        tenantName: tenantName
        name: name
        tenantDomain: tenantDomain
        email: email
      properties:
        tenantDomain:
          type: string
        tenantName:
          type: string
        email:
          type: string
        name:
          type: string
      type: object
    VerifyTrialRequest:
      example:
        password: Ab!123ab
      properties:
        password:
          type: string
      required:
      - password
      type: object
    ComplianceIssues:
      nullable: true
      properties:
        complianceIssues:
          items:
            $ref: '#/components/schemas/ComplianceIssues_complianceIssues_inner'
          type: array
      type: object
    SubmissionError:
      allOf:
      - $ref: '#/components/schemas/Error'
      - $ref: '#/components/schemas/ComplianceIssues'
    verify_trial_200_response:
      example:
        success: true
      properties:
        success:
          type: boolean
      required:
      - success
      type: object
    ComplianceIssues_complianceIssues_inner:
      properties:
        field:
          example: compute.gpuDevicesRequest
          type: string
        details:
          example: value must be no less than 3
          type: string
      required:
      - details
      - field
      type: object
